# DESCRIPTION:  The permission manager to handle permissions
# FORMAT:       Enum:
#                     "VAULT" (Vault),
#                     "GROUP_MANAGER" (Essentials GroupManager),
#                     "PERMISSIONS_EX" (PermissionsEx),
#                     "LUCK_PERMS" (LuckPerms),
#                     or "CUSTOM".
PermissionManager: "VAULT"

# DESCRIPTION:  The command executed when someone buys a permission.
# FORMAT:       String
# NOTE:         Only use this when PermissionManager is set to 'CUSTOM'.
CustomPermissionCommand: "manuaddp {PLAYER} {PERMISSION}"

# DESCRIPTION:  GUI Size
# FORMAT:       InventorySize (http://u.tabuu.nl/5mh7vwb2x).
# NOTE:         The inventory needs at least 3 rows.
GUISize: "THREE_ROWS"

# DESCRIPTION:  Whether or not the messages should be displayed as titles instead of in chat.
# FORMAT:       Boolean
UseTitle: true

# DESCRIPTION:  Whether or not zeros in the price should be replaced with their corresponding suffix.
# FORMAT:       Boolean
# NOTE:         The suffixes can be configured below.
UseNumberSuffix: false

# DESCRIPTION:  Suffixes per zero count.
# FORMAT:       'zero count': 'suffix'
NumberSuffixes:
  '3': 'k'
  '6': 'M'
  '9': 'B'

Icons:
  # DESCRIPTION:  Material of the unlocked items.
  # FORMAT:       XMaterial (http://u.tabuu.nl/5mh5duwn0).
  # NOTE:         If you do not want it to change, leave it empty.
  UnlockedMaterial: "IRON_BARS"

  # DESCRIPTION:  Materials of how node types are displayed in menus.
  # FORMAT:       XMaterial (http://u.tabuu.nl/5mh5duwn0).
  NodeTypes:
    PERMISSION: "PAPER"
    TEMPORARY_PERMISSION: "CLOCK"
    GROUP: "TOTEM_OF_UNDYING"
    TRACK: "KNOWLEDGE_BOOK"