name: PermissionShopZ
version: ${project.version}
main: nl.tabuu.permissionshopz.PermissionShopZ
description: ${project.description}
authors: [Tabuu]
website: https://www.tabuu.nl
depend: [Vault, TabuuCore]
softdepend: [GroupManager, PermissionsEx, LuckPerms]
api-version: 1.13

commands:
  permissionshopz:
    usage: /permissionshopz
    description: Opens the shop GUI.
    permission: permissionshopz.default
    aliases: [pshop, permissionshop]

  permissionshopz add:
    usage: /permissionshopz add <name> <price> <permission> [permission...]
    description: Adds a permission to the shop, the display item will be the item you hold.
    permission: permissionshopz.admin

  permissionshopz remove:
    usage: /permissionshopz remove
    description: Opens the removal GUI.
    permission: permissionshopz.admin

  permissionshopz reload:
    usage: /permissionshopz reload
    description: Reloads the config.
    permission: permissionshopz.admin

permissions:
  permissionshopz.default:
    description: Allows players to open the GUI.
    default: true

  permissionshopz.admin:
    description: Allows players to manage the permission shop.
    default: op